// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that suggests a transaction category based on transaction history and description.
 *
 * - categorizeTransaction - A function that handles the transaction categorization process.
 * - CategorizeTransactionInput - The input type for the categorizeTransaction function.
 * - CategorizeTransactionOutput - The return type for the categorizeTransaction function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CategorizeTransactionInputSchema = z.object({
  transactionDescription: z
    .string()
    .describe('A descrição da transação.'),
  transactionHistory: z
    .string()
    .describe(
      'O histórico de transações do usuário, incluindo data, descrição e categoria de transações anteriores.'
    ),
});
export type CategorizeTransactionInput = z.infer<
  typeof CategorizeTransactionInputSchema
>;

const CategorizeTransactionOutputSchema = z.object({
  suggestedCategory: z
    .string()
    .describe('A categoria sugerida para a transação.'),
  confidence: z
    .number()
    .describe(
      'Uma pontuação de confiança entre 0 e 1 indicando a certeza da categoria sugerida.'
    ),
});
export type CategorizeTransactionOutput = z.infer<
  typeof CategorizeTransactionOutputSchema
>;

export async function categorizeTransaction(
  input: CategorizeTransactionInput
): Promise<CategorizeTransactionOutput> {
  return categorizeTransactionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'categorizeTransactionPrompt',
  input: {schema: CategorizeTransactionInputSchema},
  output: {schema: CategorizeTransactionOutputSchema},
  prompt: `Você é um assistente de finanças pessoais que sugere categorias de transação com base na descrição e no histórico da transação.

Descrição da Transação: {{{transactionDescription}}}
Histórico de Transações: {{{transactionHistory}}}

Com base na descrição e no histórico da transação, sugira uma categoria para esta transação e uma pontuação de confiança entre 0 e 1.
Certifique-se de que a suggestedCategory esteja limitada a uma das seguintes opções: "Alimentação", "Transporte", "Compras", "Entretenimento", "Serviços", "Aluguel", "Salário", "Outros".

{{json output}}`,
});

const categorizeTransactionFlow = ai.defineFlow(
  {
    name: 'categorizeTransactionFlow',
    inputSchema: CategorizeTransactionInputSchema,
    outputSchema: CategorizeTransactionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
