name: Fix Git Author

on:
  push:
    branches:
      - firebase-auto 

jobs:
  fix-author:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configurar Git
        run: |
          git config user.name "Bruno Palma"
          git config user.email "br88@outlook.com"

      - name: Corrigir commit sem author
        run: |
          AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
          AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')

          if [ -z "$AUTHOR_NAME" ] || [ -z "$AUTHOR_EMAIL" ] || [ "$AUTHOR_NAME" = "Unknown" ]; then
            echo "Commit sem author detectado, corrigindo..."
            git commit --amend --no-edit --author="Bruno Palma <br88@outlook.com>"
            git push origin HEAD:main --force
          else
            echo "Author OK: $AUTHOR_NAME <$AUTHOR_EMAIL>"

      - name: Criar Pull Request para main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Firebase auto commits com author corrigido"
          branch: firebase-auto
          base: main
          title: "Merge Firebase auto commits para main"
          body: "Pull request automático gerado pelo workflow após corrigir author dos commits."
          draft: false
