name: Fix Git Author

on:
  push:
    branches:
      - main  # ajuste se seu branch for diferente

jobs:
  fix-author:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configurar Git
        run: |
          git config user.name "Vercel Deploy Bot"
          git config user.email "br88@outlook.com"

      - name: Corrigir commit sem author
        run: |
          AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
          AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')

          if [ -z "$AUTHOR_NAME" ] || [ -z "$AUTHOR_EMAIL" ] || [ "$AUTHOR_NAME" = "Unknown" ]; then
            echo "Commit sem author detectado, corrigindo..."
            git commit --amend --no-edit --author="Vercel Deploy Bot <br88@outlook.com>"
            git push origin HEAD:main --force
          else
            echo "Author OK: $AUTHOR_NAME <$AUTHOR_EMAIL>"
          fi
